//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MutualFund.MutualFundService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MutualFundService.IMutualFundService")]
    public interface IMutualFundService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMutualFundService/GetMutualFundData", ReplyAction="http://tempuri.org/IMutualFundService/GetMutualFundDataResponse")]
        System.Data.DataTable GetMutualFundData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMutualFundService/GetMutualFundData", ReplyAction="http://tempuri.org/IMutualFundService/GetMutualFundDataResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetMutualFundDataAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMutualFundServiceChannel : MutualFund.MutualFundService.IMutualFundService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MutualFundServiceClient : System.ServiceModel.ClientBase<MutualFund.MutualFundService.IMutualFundService>, MutualFund.MutualFundService.IMutualFundService {
        
        public MutualFundServiceClient() {
        }
        
        public MutualFundServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MutualFundServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MutualFundServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MutualFundServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable GetMutualFundData() {
            return base.Channel.GetMutualFundData();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetMutualFundDataAsync() {
            return base.Channel.GetMutualFundDataAsync();
        }
    }
}
